export const districtsData = [
  { id: 'beykoz', name: 'Beykoz', x: 72.8, y: 28.1, svgId: 'beykoz', labelSize: 38 },
  { id: 'sariyer', name: 'Sarıyer', x: 45.2, y: 25.0, svgId: 'sariyer', labelSize: 35 },
  { id: 'eyup', name: 'Eyüpsultan', x: 28.6, y: 20.2, svgId: 'eyup', labelSize: 28, labelWidth: 158 },
  { id: 'kadikoy', name: 'Kadıköy', x: 58.9, y: 72.6, svgId: 'kadikoy', labelSize: 31, labelWidth: 124 },
  { id: 'maltepe', name: 'Maltepe', x: 70.8, y: 85.5, svgId: 'maltepe', labelSize: 31 },
  { id: 'uskudar', name: 'Üsküdar', x: 58.7, y: 51.0, svgId: 'uskudar', labelSize: 29, labelWidth: 108 },
  { id: 'bayrampasa', name: 'Bayrampaşa', x: 33.1, y: 52.6, svgId: 'bayrampasa', labelSize: 21, labelWidth: 126 },
  { id: 'fatih', name: 'Fatih', x: 41.0, y: 64.9, svgId: 'fatih', labelSize: 34 },
  { id: 'zeytinburnu', name: 'Zeytinburnu', x: 29.9, y: 70.1, svgId: 'zeytinburnu', labelSize: 23, labelWidth: 140 },
  { id: 'besiktas', name: 'Beşiktaş', x: 48.1, y: 48.0, svgId: 'besiktas', labelSize: 31, labelWidth: 128 },
  { id: 'beyoglu', name: 'Beyoğlu', x: 43.2, y: 55.4, svgId: 'beyoglu', labelSize: 32 },
  { id: 'sisli', name: 'Şişli', x: 40.7, y: 44.9, svgId: 'sisli', labelSize: 34 },
  { id: 'sultangazi', name: 'Sultangazi', x: 32.3, y: 34.1, svgId: 'sultangazi', labelSize: 24, labelWidth: 132 },
  { id: 'umraniye', name: 'Ümraniye', x: 72.8, y: 51.9, svgId: 'umraniye', labelSize: 34, labelWidth: 158 },
  { id: 'kagithane', name: 'Kağıthane', x: 45.5, y: 35.8, svgId: 'kagithane', labelSize: 27, labelWidth: 136 },
  { id: 'atasehir', name: 'Ataşehir', x: 73.4, y: 69.8, svgId: 'atasehir', labelSize: 31, labelWidth: 148 },
  { id: 'gaziosmanpasa', name: 'Gaziosmanpaşa', x: 30.7, y: 40.9, svgId: 'gaziosmanpasa', labelSize: 16, labelWidth: 122 },
];
