export const districtsData = [
  { id: 'kadikoy', name: 'Kadıköy', x: 53.9, y: 73.9, pathIndex: 2, mapPaths: { 'bigMap.svg': 2, 'smallMap.svg': 2 } },
  { id: 'uskudar', name: 'Üsküdar', x: 52.6, y: 62.2, pathIndex: 8, mapPaths: { 'bigMap.svg': 8, 'smallMap.svg': 1 } },
  { id: 'atasehir', name: 'Ataşehir', x: 60.6, y: 73.4, mapPaths: { 'smallMap.svg': 9 } },
  { id: 'umraniye', name: 'Ümraniye', x: 60.5, y: 63.9, mapPaths: { 'smallMap.svg': 6 } },
  { id: 'maltepe', name: 'Maltepe', x: 61.7, y: 82.4, mapPaths: { 'smallMap.svg': 3 } },
  { id: 'kartal', name: 'Kartal', x: 65.4, y: 88.5, mapPaths: { 'smallMap.svg': 4 } },
  { id: 'beykoz', name: 'Beykoz', x: 72.2, y: 54.3, mapPaths: { 'smallMap.svg': 5 } },
  { id: 'pendik', name: 'Pendik', x: 72.3, y: 70.3, mapPaths: { 'smallMap.svg': 7 } },
  { id: 'tuzla', name: 'Tuzla', x: 72.6, y: 77.2, mapPaths: { 'smallMap.svg': 8 } },
  { id: 'sile', name: 'Şile', x: 67.1, y: 39.7, mapPaths: { 'smallMap.svg': 0 } },
  { id: 'besiktas', name: 'Beşiktaş', x: 46.5, y: 51.6, pathIndex: 16, mapPaths: { 'bigMap.svg': 16, 'smallMap.svg': 13 } },
  { id: 'beyoglu', name: 'Beyoğlu', x: 37.4, y: 42.6, pathIndex: 20, mapPaths: { 'bigMap.svg': 20, 'smallMap.svg': 17 } },
  { id: 'sisli', name: 'Şişli', x: 39.5, y: 57.8, pathIndex: 34, mapPaths: { 'bigMap.svg': 34, 'smallMap.svg': 20 } },
  { id: 'fatih', name: 'Fatih', x: 36.9, y: 55.7, pathIndex: 25, mapPaths: { 'bigMap.svg': 25, 'smallMap.svg': 21 } },
  { id: 'zeytinburnu', name: 'Zeytinburnu', x: 34.9, y: 67.3, pathIndex: 33, mapPaths: { 'bigMap.svg': 33, 'smallMap.svg': 24 } },
  { id: 'bakirkoy', name: 'Bakırköy', x: 28.9, y: 64.2, pathIndex: 32, mapPaths: { 'bigMap.svg': 32, 'smallMap.svg': 26 } },
  { id: 'eyup', name: 'Eyüp', x: 50.8, y: 31.7, pathIndex: 18, mapPaths: { 'bigMap.svg': 18, 'smallMap.svg': 10 } },
  { id: 'sariyer', name: 'Sarıyer', x: 37.6, y: 32.7, pathIndex: 37, mapPaths: { 'bigMap.svg': 37, 'smallMap.svg': 15 } },
];
